app/models/bulk_ship.py
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import orm

from app.database import db
from .utils import ModelMixin, generate_uuid
from app import schema as s


class BulkShip(db.Model, ModelMixin):
    __tablename__ = "bulk_ships"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)

    user_id: orm.Mapped[int] = orm.mapped_column(sa.Integer, sa.ForeignKey("users.id"))
    uuid: orm.Mapped[str] = orm.mapped_column(
        sa.String(36),
        default=generate_uuid,
        index=True,
    )
    status: orm.Mapped[str] = orm.mapped_column(
        default=s.BulkShipStatus.DRAFT.value,
    )
    name = orm.mapped_column(sa.String(256), default="")
    is_deleted: orm.Mapped[bool] = orm.mapped_column(sa.Boolean, default=False)

    created_at: orm.Mapped[datetime] = orm.mapped_column(
        sa.DateTime,
        default=datetime.now,
    )
    absolute_file_path: orm.Mapped[str] = orm.mapped_column(sa.String(512))
    uploaded_file_path: orm.Mapped[str] = orm.mapped_column(sa.String(512))

    def __repr__(self):
        return f"<{self.id}>"

app/forms/bulk_ship.py
from flask_wtf import FlaskForm
from wtforms import (
    HiddenField,
    StringField,
    FileField,
)
from wtforms.validators import DataRequired, Length


class NewBulkShipForm(FlaskForm):
    name = StringField(
        "Name", [DataRequired(), Length(max=256)], render_kw={"placeholder": "Name"}
    )
    exel_file = FileField("Exel file", [DataRequired()])


class EditBulkShipForm(FlaskForm):
    uuid = HiddenField("UUID", [DataRequired()])

app/controllers/bulk_ship/__init__.py
# flake8: noqa F401
from .validator import validate_bulk_ship_exel
from .creator import create_ship_requests_by_address
from .save_file import save_exel_file

app/schema/bulk_ship/__init__.py
# flake8: noqa F401
from .bulk_ship import BulkShipStatus
from .validator import WhProduct, ValidateBulkShipResult

app/views/bulk_ship.py
# flake8: noqa E501

import io
import os
from datetime import datetime

from flask import (
    Blueprint,
    render_template,
    render_template_string,
    request,
    flash,
    send_file,
)

from flask_login import login_required, current_user
import pandas as pd
from openpyxl import Workbook
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter
import sqlalchemy as sa

from app.controllers import (
    create_pagination,
    role_required,
    create_ship_requests_by_address,
    save_exel_file,
)

from app import models as m, db
from app import schema as s
from app import forms as f
from app.controllers import validate_bulk_ship_exel
from app.logger import log
from .utils import RELOAD_PAGE_SCRIPT, create_match


bulk_ship_bp = Blueprint("bulk_ship", __name__, url_prefix="/bulk-ship")


@bulk_ship_bp.route("/", methods=["GET"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def get_all():

    q = request.args.get("q", type=str, default="")

    where_stmt = sa.and_(
        m.BulkShip.is_deleted.is_(False), m.BulkShip.user_id == current_user.id
    )

    if current_user.role_obj.role_name == s.UserRole.ADMIN.value:
        where_stmt = sa.and_(m.BulkShip.is_deleted.is_(False))

    if q:
        where_stmt = sa.and_(
            where_stmt,
            sa.or_(
                m.BulkShip.name.ilike(f"%{q}%"),
            ),
        )

    query = (
        sa.select(m.BulkShip).where(where_stmt).order_by(m.BulkShip.created_at.desc())
    )
    count_query = sa.select(sa.func.count()).where(where_stmt).select_from(m.BulkShip)

    pagination = create_pagination(total=db.session.scalar(count_query))
    bulk_ships = db.session.scalars(
        query.offset((pagination.page - 1) * pagination.per_page).limit(
            pagination.per_page
        )
    )

    return render_template(
        "bulk_ship/bulk_ships.html",
        bulk_ships=bulk_ships,
        page=pagination,
        q=q,
    )


@bulk_ship_bp.route("/download-template", methods=["GET"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def download_template():

    wb = Workbook()
    main_sheet = wb.active
    main_sheet.title = "Main"

    # Create the product sheet
    products = db.session.scalars(sa.select(m.Product))
    product_count = db.session.scalar(sa.select(sa.func.count()).select_from(m.Product))
    groups_sheet = wb.create_sheet(title="Groups")
    for col, product in enumerate(products, start=1):
        col_letter = get_column_letter(col)
        groups_sheet[f"{col_letter}1"] = product.SKU
        wh_products = [
            wh_prod
            for wh_prod in product.warehouse_products
            if wh_prod.available_quantity != 0
            and wh_prod.group.name != s.Events.name.value
        ]
        for row, wh_product in enumerate(wh_products, start=2):
            groups_sheet[f"{col_letter}{row}"] = (
                f"{wh_product.group.name} ({wh_product.available_quantity})"
            )

    store_categories = db.session.scalars(
        sa.select(m.StoreCategory).where(m.StoreCategory.name.not_ilike("%Event%"))
    )
    count_store_categories = db.session.scalar(
        sa.select(sa.func.count()).select_from(m.StoreCategory)
    )

    # Create the store categories sheet
    store_categories_sheet = wb.create_sheet(title="Stores")
    for col, store_category in enumerate(store_categories, start=1):
        col_letter = get_column_letter(col)
        store_categories_sheet[f"{col_letter}1"] = store_category.name
        for row, store in enumerate(store_category.stores, start=2):
            store_categories_sheet[f"{col_letter}{row}"] = store.store_name

    # Set up the main form sheet
    main_sheet["A1"] = "SKU"
    main_sheet["B1"] = "Group"
    main_sheet["C1"] = "Quantity"
    main_sheet["D1"] = "Store Category"
    main_sheet["E1"] = "Store name"

    # Add dropdowns for product SKUs
    last_let = get_column_letter(product_count)
    country_dv = DataValidation(
        type="list",
        formula1=f"{groups_sheet.title}!$A$1:${last_let}$1",
        allow_blank=True,
        showDropDown=False,
    )
    main_sheet.add_data_validation(country_dv)
    country_dv.add("A2:A100")

    # Add dropdowns for store category
    store_last_let = get_column_letter(count_store_categories)
    store_category_dv = DataValidation(
        type="list",
        formula1=f"{store_categories_sheet.title}!$A$1:${store_last_let}$1",
        allow_blank=True,
        showDropDown=False,
    )
    main_sheet.add_data_validation(store_category_dv)
    store_category_dv.add("D2:D100")

    # Create data validation for cities using named ranges
    # offset( reference, rows, cols, height, width)
    # OFFSET(Data!A1,1,MATCH(A2,Data!A1:C1,0) -1,10,1)"

    # Create the named ranges
    for row in range(2, 100):
        store_category_dv = DataValidation(
            type="list",
            formula1=f"OFFSET({store_categories_sheet.title}!A1,1,{create_match('D' + str(row), store_categories_sheet.title, count_store_categories)},500,1)",
            showDropDown=False,
            allow_blank=True,
        )
        main_sheet.add_data_validation(store_category_dv)
        store_category_dv.add(f"E{row}")

        groups_dv = DataValidation(
            type="list",
            formula1=f"OFFSET({groups_sheet.title}!A1,1,{create_match('A' + str(row),groups_sheet.title, product_count)},50,1)",
            showDropDown=False,
            allow_blank=False,
            showErrorMessage=True,
        )
        groups_dv.error = "Please select a valid group"
        groups_dv.errorTitle = "Invalid group"
        main_sheet.add_data_validation(groups_dv)
        groups_dv.add(f"B{row}")

    # Save the workbook to a BytesIO object
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)

    # Step 7: Serve the Excel file as a download
    return send_file(
        output,
        as_attachment=True,
        download_name="empty_form_with_dropdowns.xlsx",
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )


@bulk_ship_bp.route("/create", methods=["GET"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def get_create_modal():
    """htmx"""
    form = f.NewBulkShipForm()
    return render_template("bulk_ship/modal_add.html", form=form)


@bulk_ship_bp.route("/create", methods=["POST"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def create():
    """htmx"""
    form = f.NewBulkShipForm()
    if not form.validate_on_submit():
        log(log.ERROR, "Form validation failed", form.errors)

        return render_template(
            "bulk_ship/modal_add.html", form=form, errors=form.errors
        )

    file = request.files.get("exel_file")

    if not file:
        log(log.ERROR, "Form validation failed", form.errors)
        return render_template(
            "bulk_ship/modal_add.html", form=form, errors={"file": ["File is required"]}
        )

    result = s.ValidateBulkShipResult(errors=dict())
    file.seek(0)

    # why we forst save the file and then validate it because after validation file change and save not work properly
    absolute_file_path, upload_file_path = save_exel_file(file, result)
    if result.errors:
        log(log.ERROR, "Exel save failed", result.errors)
        return render_template(
            "bulk_ship/modal_add.html", form=form, errors=result.errors
        )

    wh_products = validate_bulk_ship_exel(file, result)

    if result.errors:
        log(log.ERROR, "Exel validation failed", result.errors)

        os.remove(absolute_file_path)

        for stor_id in result.new_stores_ids:
            store = db.session.get(m.Store, int(stor_id))
            if store:
                db.session.delete(store)

            db.session.commit()
        return render_template(
            "bulk_ship/modal_add.html", form=form, errors=result.errors
        )

    try:
        create_ship_requests_by_address(wh_products)
    except Exception as e:
        log(log.ERROR, "Bulk ship creation failed", str(e))
        return render_template(
            "toast.html", message="Bulk ship creation failed", category="error"
        )

    # TODO mybe we need to notify warehouse manager about new bulk ship

    m.BulkShip(
        user_id=current_user.id,
        status=s.BulkShipStatus.DRAFT.value,
        name=form.name.data,
        absolute_file_path=str(absolute_file_path),
        uploaded_file_path=str(upload_file_path),
    ).save()

    flash("Bulk ship created successfully", category="success")

    return render_template_string(RELOAD_PAGE_SCRIPT)


@bulk_ship_bp.route("/<uuid>/download-template", methods=["GET"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def bulk_ship_template_download(uuid: str):

    bulk_ship = db.session.scalar(sa.select(m.BulkShip).where(m.BulkShip.uuid == uuid))
    if not bulk_ship or bulk_ship.is_deleted:
        log(log.ERROR, "Bulk ship not found [%s]", uuid)
        flash("Bulk ship not found", category="danger")
        return "", 404

    if not os.path.exists(bulk_ship.absolute_file_path):
        log(log.ERROR, "File not found [%s]", bulk_ship.absolute_file_path)
        flash("File not found", category="danger")
        return "", 404

    return send_file(
        bulk_ship.uploaded_file_path,
        as_attachment=True,
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )


@bulk_ship_bp.route("/<uuid>/view", methods=["GET"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.WAREHOUSE_MANAGER.value], has_bulk_ship=True
)
def view(uuid: str):

app/views/main.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
@login_required
def index():
    return redirect(url_for("product.get_all"))


@main_blueprint.route("/no-content")
@login_required
def no_content():
    return "", 200

app/templates/bulk_ship/bulk_ships.html
<!-- prettier-ignore -->
{% extends 'base.html' %}
{% block content %}

<div class="relative overflow-visible shadow-md sm:rounded-lg overflow-x-auto min-h-half">
  <div class="flex sm:gap-5 flex-wrap">
    <div class="flex justify-between  w-full py-4 items-center mx-2 ">
      <div class="flex items-center justify-center py-4 bg-white dark:bg-gray-800 flex-wrap gap-4">
        <label for="table-search" class="sr-only">Search</label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
            <!-- prettier-ignore -->
            <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor"
              viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                clip-rule="evenodd"></path>
            </svg>
          </div>
          <!-- prettier-ignore -->
           <form action="" method="get"  class="flex">
            <input {% if q %}value={{ q }}{% endif %} type="text" name="q" 
            class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
            placeholder="Search for inbound orders" />
            <button type="sumbit" 
          class="px-3 py-2 text-xs text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 ml-2 font-medium rounded-lg text-center inline-flex items-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><svg
            class="w-5 h-5 text-white-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            stroke-width="1.5" stroke="currentColor" class="w-6 h-6 ml-0 mr-1">
            <path stroke-linecap="round" stroke-linejoin="round"
              d="M15.75 15.75l-2.489-2.489m0 0a3.375 3.375 0 10-4.773-4.773 3.375 3.375 0 004.774 4.774zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>Search</button>
           </form>
          
        </div>
        <!-- prettier-ignore -->
        
      </div>
      <div class="flex gap-4">
        <button  type="button"  class="download-bulk-ship-template text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 inline-flex items-center">
          
            Download example template
          </button>
        <!-- </form> -->
        <button type="button" hx-get="{{ url_for('bulk_ship.get_create_modal') }}" hx-trigger="click" hx-swap="beforeend"
          hx-target="body" hx-indicator="#htmx-spinner"
          class="inline-flex items-center justify-center  px-3 h-10 text-sm font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 sm:w-auto dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          <svg class="w-5 h-5 mr-2 " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z"
              clip-rule="evenodd"></path>
          </svg>
          Upload template
        </button>
      </div>
      
      
    </div>
  </div>
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          <div class="w-full flex justify-center" >Name</div>
          </th>
        <th scope="col" class="px-6 py-3"><div class="w-full flex justify-center" >Action</div></th>
      </tr>
    </thead>
    <tbody>
      {% for ship in bulk_ships %}
      <tr>
        <td class="px-6 py-4 ">  <div class="w-full flex justify-center" >
          {{ ship.name }}
        </div> </td>
        <td class="px-6 py-4 justify-center">
          <div class="w-full flex justify-center gap-4 ">
            <button type="button" hx-get="{{ url_for('bulk_ship.view', uuid=ship.uuid) }}" hx-trigger="click" hx-swap="beforeend"
            hx-target="body" hx-indicator="#htmx-spinner"  class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">View</button>
            <button type="button" bulk-ship-uuid="{{ ship.uuid }}"
              class="download-bulk-ship-template focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:focus:ring-yellow-900">
              
                Download template
              </button>
            <button type="button" bulk-ship-uuid="{{ ship.uuid }}"
              class="delete-bulk-ship-btn focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5  dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Delete</button>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% if page.pages > 1 %}
<div class="container content-center mt-3 flex bg-white dark:bg-gray-800">
  <nav aria-label="Page navigation example" class="mx-auto">
    <ul class="inline-flex items-center -space-x-px">
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page=1&q={{page.query}}"
          class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <span class="sr-only">First</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd"
              d="M15.79 14.77a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L11.832 10l3.938 3.71a.75.75 0 01.02 1.06zm-6 0a.75.75 0 01-1.06.02l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 111.04 1.08L5.832 10l3.938 3.71a.75.75 0 01.02 1.06z"
              clip-rule="evenodd" />
          </svg>
        </a>

      </li>
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page={{page.page-1 if page.page > 1 else 1}}&q={{page.query}}"
          class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <span class="sr-only">Previous</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd"
              d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z"
              clip-rule="evenodd" />
          </svg>
        </a>
      </li>

      <!-- prettier-ignore -->
      {% for p in page.pages_for_links %}
      <li>
        <!-- prettier-ignore -->
        {% if p == page.page %}
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page={{p}}&q={{page.query}}" aria-current="page"
          class="z-10 px-3 py-2 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{p}}</a>
        {% else %}
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page={{p}}&q={{page.query}}"
          class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{p}}</a>
        {% endif %}
      </li>
      {% endfor %}

      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page={{page.page+1 if page.page < page.pages else page.pages}}&q={{page.query}}"
          class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <!-- prettier-ignore -->
          <span class="sr-only">Next</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd"
              d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
              clip-rule="evenodd" />
          </svg>
        </a>
      </li>
      <li>
        <!-- prettier-ignore -->
        <a href="{{ url_for('bulk_ship.get_all') }}?page={{page.pages}}&q={{page.query}}"
          class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <!-- prettier-ignore -->
          <span class="sr-only">Last</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
            <path fill-rule="evenodd"
              d="M10.21 14.77a.75.75 0 01.02-1.06L14.168 10 10.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
              clip-rule="evenodd" />
            <path fill-rule="evenodd"
              d="M4.21 14.77a.75.75 0 01.02-1.06L8.168 10 4.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z"
              clip-rule="evenodd" />
          </svg>
        </a>
      </li>
    </ul>
  </nav>
</div>
</div>
{% endif %}

</div>

<!-- prettier-ignore -->
{% endblock %}
<!-- prettier-ignore -->
{% block scripts %}
<script src="{{ url_for('static', filename='js/bulk_ship.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/bulk_ship/modal_view.html
<!-- View inbound order modal -->
<!-- prettier-ignore-->
<div tabindex="-1" id="bulk-ship-modal-view" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click" hx-swap="delete"
hx-target="#bulk-ship-modal-view" hx-indicator="#htmx-spinner"
  class="fixed bg-opacity-80 bg-gray-600 top-0 left-0 right-0 z-50 items-center justify-center w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-full max-h-full justify-end items-end flex">
  <div class="relative  max-h-full" onclick="event.stopPropagation();">
    <style>
      table, th, td {
          border: 1px solid #94a3b8;
          border-collapse: collapse;
      }
      th, td {
          padding: 8px;
          text-align: left;
      }
  </style>
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">View</h3>
        <div class="flex align-baseline gap-4">
          <button type="button" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click" hx-swap="delete"
            hx-target="#bulk-ship-modal-view" hx-indicator="#htmx-spinner"
            class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
            </svg>
          </button>
        </div>
      </div>
      <div class="p-4 flex justify-center w-full">{{ excel_html|safe }}</div>
    </div>
  </div>
</div>