app/views/pickup_inbound.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_required
import sqlalchemy as sa
from sqlalchemy import desc
from app.controllers import create_pagination, role_required

from app import schema as s
from app import models as m, db
from app import forms as f
from app.logger import log

from app.constants import DELIVERY_AGENT_ROLES

# NOTE pickup inbound IS inbound order. Meaning goods going from supplier to warehouse
pickup_inbound_blueprint = Blueprint(
    "pickup_inbound", __name__, url_prefix="/pickup_inbound"
)


def get_pickup_inbound():
    filter_pickup_inbound = s.FilterInboundOrder.model_validate(dict(request.args))

    query = m.InboundOrder.select().order_by(desc(m.InboundOrder.id))
    count_query = sa.select(sa.func.count()).select_from(m.InboundOrder)

    if filter_pickup_inbound.q:
        query = query.where(
            m.InboundOrder.title.ilike(f"%{filter_pickup_inbound.q}%")
            | m.InboundOrder.order_id.ilike(f"%{filter_pickup_inbound.q}%")
        )

        count_query = count_query.where(
            m.InboundOrder.title.ilike(f"%{filter_pickup_inbound.q}%")
            | m.InboundOrder.order_id.ilike(f"%{filter_pickup_inbound.q}%")
        )

    if filter_pickup_inbound.status:
        query = query.where(
            m.InboundOrder.status == s.InboundOrderStatus(filter_pickup_inbound.status)
        )

        count_query = count_query.where(
            m.InboundOrder.status == s.InboundOrderStatus(filter_pickup_inbound.status)
        )

    pagination = create_pagination(total=db.session.scalar(count_query))

    orders = db.session.scalars(
        query.offset((pagination.page - 1) * pagination.per_page).limit(
            pagination.per_page
        )
    )
    return pagination, orders


@pickup_inbound_blueprint.route("/", methods=["GET"])
@login_required
@role_required(DELIVERY_AGENT_ROLES)
def get_all():
    form_edit: f.ShipRequestForm = f.ShipRequestForm()
    return render_template(
        "pickup_inbound/pickup_inbounds.html",
        form_edit=form_edit,
        suppliers=db.session.scalars(m.Supplier.select().order_by(m.Supplier.id)),
        delivery_agents=db.session.scalars(
            m.DeliveryAgent.select().order_by(m.DeliveryAgent.id)
        ),
        warehouses=db.session.scalars(m.Warehouse.select().order_by(m.Warehouse.id)),
        inbound_orders_status=s.InboundOrderStatus,
    )


@pickup_inbound_blueprint.route("/pickup", methods=["POST"])
@login_required
@role_required(DELIVERY_AGENT_ROLES)
def pickup():
    form_pickup: f.InboundOrderPickupForm = f.InboundOrderPickupForm()

    if not form_pickup.validate_on_submit():
        log(log.ERROR, "Pickup inbound form errors: [%s]", form_pickup.errors)
        flash(f"{form_pickup.errors}", "danger")
        return redirect(url_for("pickup_inbound.get_all"))

    inbound_order: m.InboundOrder = db.session.get(
        m.InboundOrder, int(form_pickup.inbound_order_id.data)
    )

    if not inbound_order:
        log(
            log.INFO,
            "There is no inbound order with id: [%s]",
            form_pickup.inbound_order_id.data,
        )
        flash("There is no such inbound order", "danger")
        return redirect(url_for("pickup_inbound.get_all"))

    if inbound_order.status == s.InboundOrderStatus.in_transit:
        log(
            log.INFO,
            "Inbound order with id: [%s] is already in transit",
            form_pickup.inbound_order_id.data,
        )
        flash("Inbound order is already in transit", "danger")
        return redirect(url_for("pickup_inbound.get_all"))

    # new fields
    inbound_order.proof_of_delivery = form_pickup.proof_of_delivery.data
    inbound_order.tracking = form_pickup.tracking.data

    inbound_order.status = s.InboundOrderStatus.in_transit
    inbound_order.da_notes = form_pickup.da_notes.data
    inbound_order.save(False)

    report_skus: list[m.ReportSKU] = db.session.scalars(
        m.ReportSKU.select().where(
            m.ReportSKU.inbound_order_id == inbound_order.id,
            m.ReportSKU.status == "Products allocated. Inbound order assigned.",
        )
    )
    for report_sku in report_skus:
        m.ReportSKU(
            product_id=report_sku.product_id,
            inbound_order=inbound_order,
            type=s.ReportSKUType.inbound_order.value,
            status="Inbound order in transit",
        ).save(False)

    db.session.commit()

    log(log.INFO, "Inbound order pickup done. Inbound order: [%s]", inbound_order)
    flash("Inbound order pickup done!", "success")
    return redirect(url_for("pickup_inbound.get_all"))


@pickup_inbound_blueprint.route(
    "/sort", methods=["GET", "POST"]
)  # TODO move pickup inbound sort to GET with params
@login_required
@role_required(DELIVERY_AGENT_ROLES)
def sort():
    pagination, orders = get_pickup_inbound()

    return render_template(
        "pickup_inbound/pickup_inbounds_table.html",
        page=pagination,
        orders=orders,
    )

app/templates/pickup_inbound/edit.html
<!-- Edit pickup inbound modal -->
<!-- prettier-ignore-->
<div id="editPickupInboundModal" tabindex="-1" aria-hidden="true"
  class="fixed top-0 left-0 right-0 z-50 items-center justify-center hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <form action="{{url_for('pickup_inbound.package_info')}}" id="pickup-inbound-edit-form" method="post"
      class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      {{ form_edit.hidden_tag() }}
      <input type="hidden" name="inbound_order_id" id="pickup-inbound-edit-id" value="0" />
      <input type="hidden" name="recieved_products" id="pickup-inbound-edit-recieved-products" value="" />
      <input type="hidden" name="next_url" id="inbound-order-edit-next_url" value="" />
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Edit pickup inbound </h3>
      </div>
      <!-- Modal body -->
      <div id="pickup-inbound-edit-add-container">
      </div>
      <div class="p-6 space-y-6 border-t">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6 sm:col-span-3">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Quantity Per
              Wrap</label>
            <input type="text" name="quantity_per_wrap"
              class="pickup-inbound-edit-quantity shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Quantity" required>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Quantity Of Wraps
              Per Carton</label>
            <input type="text" name="quantity_wrap_carton"
              class="pickup-inbound-edit-quantity shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Quantity" required>
          </div>
          <div class="col-span-6 sm:col-span-6">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Quantity Of Cartons
              Per Master Carton (Optional)</label>
            <input type="text" name="quantity_carton_master"
              class="pickup-inbound-edit-quantity shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Quantity">
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button id="pickup-inbound-submit-btn" name="submit" type="submit" class="hidden"></button>
        <button id="pickup-inbound-save-products-btn" name="save-products" type="button"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Save all </button>
      </div>
    </form>
  </div>
</div>

app/templates/pickup_inbound/pickup_inbounds.html
<!-- prettier-ignore -->
{% extends 'base.html' %}
{% block content %}
<div class="relative overflow-visible shadow-md sm:rounded-lg overflow-x-auto min-h-half">
  <button id="table-report-loader" hx-trigger="click" hx-get="{{ url_for('pickup_inbound.sort') }}"
    hx-target="#reports-table" hx-indicator="#htmx-spinner" class="hidden"></button>
  <div class="flex flex-wrap sm:gap-5">
    <div class="flex gap-4 items-center justify-start py-4 bg-white dark:bg-gray-800 px-4">
      <label for="table-search" class="sr-only">Search</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
          {% include "icon/eyeglass_1.html" %}
        </div>
        <input name="q" hx-trigger="keyup changed delay:500ms" hx-target="#reports-table" hx-swap="innerHTML"
          hx-include="[name='status']" hx-get="{{ url_for('pickup_inbound.sort') }}" hx-indicator="#htmx-spinner"
          type="search" id="table-search-assign" placeholder="Search"
          class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
      </div>
    </div>
    <div class="flex flex-wrap py-4 bg-white dark:bg-gray-800">
      <!-- prettier-ignore -->
      <select id="report-assigns-group-from" hx-trigger="change" hx-swap="innerHTML" hx-target="#reports-table"
        name="status" hx-include="[name='q']" hx-get="{{ url_for('pickup_inbound.sort') }}" hx-indicator="#htmx-spinner"
        class="events-filter-status mr-2 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option value="" disabled selected>Status</option>
        <option value="">Default Value</option>
        {% for status in inbound_orders_status %}
        <option value="{{ status.value }}">{{ status.value }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div id="reports-table"></div>
  <div class="htmx-indicator flex justify-center items-center" id="htmx-spinner">
    {% include "icon/spinner.html" %}htmx-spinner
  </div>

</div>

{% include 'pickup_inbound/view.html' %}

<!-- prettier-ignore -->
{% endblock %}
<!-- prettier-ignore -->
{% block scripts %}
<script src="{{ url_for('static', filename='js/pickup_inbound.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/pickup_inbound/pickup_inbounds_table.html
<div id="events-table">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">#</th>
        <th scope="col" class="px-6 py-3">Order ID</th>
        <th scope="col" class="px-6 py-3">Order title</th>
        <th scope="col" class="px-6 py-3">Active date</th>
        <th scope="col" class="px-6 py-3">Active time</th>
        <th scope="col" class="px-6 py-3">Status</th>
        <th scope="col" class="px-6 py-3">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for inbound_order in orders %}
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
        <td class="w-4 p-4">
          <div class="flex items-center">
            {{ loop.index + page.skip }}
          </div>
        </td>
        <td scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
          <div class="pl-3">
            <div class="text-base font-semibold">{{ inbound_order.order_id }}</div>
          </div>
        </td>
        <td scope="row" class="p-4 text-base font-normal text-gray-900 whitespace-nowrap dark:text-white">
          <div class="pl-3">
            <div class="text-base font-semibold">{{ inbound_order.title }}</div>
          </div>
        </td>
        <td scope="row" class="p-4 text-base font-normal text-gray-900 whitespace-nowrap dark:text-white">
          <div class="pl-3">
            <div class="text-base font-semibold">{{ inbound_order.active_date }}</div>
          </div>
        </td>
        <td scope="row" class="p-4 text-base font-normal text-gray-900 whitespace-nowrap dark:text-white">
          <div class="pl-3">
            <div class="text-base font-semibold">{{ inbound_order.active_time }}</div>
          </div>
        </td>
        <td scope="row" class="p-4 text-base font-normal text-gray-900 whitespace-nowrap dark:text-white">
          <div class="pl-3">
            <div class="text-base font-semibold status-{{inbound_order.status.name}}">{{ inbound_order.status.value }}
            </div>
          </div>
        </td>
        <td class="p-4 space-x-2 whitespace-nowrap">
          <button data-pickup-inbound-id={{ inbound_order.id }} data-target="{{inbound_order.json}}" type="button"
            class="pickup-inbound-view-button  inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
            <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 576 512" xmlns="http://www.w3.org/2000/svg">
              <path
                d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z"
                clip-rule="evenodd"></path>
            </svg>
            View
          </button>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>


  {% if page.pages > 1 %}
  <div class="container content-center mt-3 flex bg-white dark:bg-gray-800">
    <nav aria-label="Page navigation example" class="mx-auto">
      <ul class="inline-flex items-center -space-x-px">
        <li>
          <button hx-get="{{ url_for('pickup_inbound.sort') }}?page=1&q={{page.query}}" hx-trigger="click"
            hx-target="#reports-table" hx-indicator="#htmx-spinner"
            class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <span class="sr-only">First</span>
            {% include "icon/left_arrow_double.html" %}
          </button>
        </li>
        <li>
          <button
            hx-get="{{ url_for('pickup_inbound.sort') }}?page={{page.page-1 if page.page > 1 else 1}}&q={{page.query}}"
            hx-trigger="click" hx-target="#reports-table" hx-indicator="#htmx-spinner"
            class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <span class="sr-only">Previous</span>
            {% include "icon/left_arrow.html" %}
          </button>
        </li>

        <!-- prettier-ignore -->
        {% for p in page.pages_for_links %}
        <li>
          <!-- prettier-ignore -->
          {% if p == page.page %}
          <button hx-get="{{ url_for('pickup_inbound.sort') }}?page={{p}}&q={{page.query}}" hx-trigger="click"
            hx-target="#reports-table" hx-indicator="#htmx-spinner" aria-current="page"
            class="z-10 px-3 py-2 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">
            {{p}}
          </button>
          {% else %}
          <button hx-get="{{ url_for('pickup_inbound.sort') }}?page={{p}}&q={{page.query}}" hx-trigger="click"
            hx-target="#reports-table" hx-indicator="#htmx-spinner"
            class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            {{p}}
          </button>
          {% endif %}
        </li>
        {% endfor %}
        <li>
          <button
            hx-get="{{ url_for('pickup_inbound.sort') }}?page={{page.page+1 if page.page < page.pages else page.pages}}&q={{page.query}}"
            hx-trigger="click" hx-target="#reports-table" hx-indicator="#htmx-spinner"
            class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <!-- prettier-ignore -->
            <span class="sr-only">Next</span>
            {% include "icon/right_arrow.html" %}
          </button>
        </li>
        <li>
          <button hx-get="{{ url_for('pickup_inbound.sort') }}?page={{page.pages}}&q={{page.query}}" hx-trigger="click"
            hx-target="#reports-table" hx-indicator="#htmx-spinner
            class=" block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg
            hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400
            dark:hover:bg-gray-700 dark:hover:text-white">
            <!-- prettier-ignore -->
            <span class="sr-only">Last</span>
            {% include "icon/right_arrow_double.html" %}
          </button>
        </li>
      </ul>
    </nav>
  </div>
  {% endif %}
</div>