app/models/store.py
from typing import TYPE_CHECKING
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import orm

from app.database import db
from app import schema as s
from .utils import ModelMixin

if TYPE_CHECKING:
    from .store_category import StoreCategory


class Store(db.Model, ModelMixin):
    __tablename__ = "stores"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)

    # Foreign keys
    user_id: orm.Mapped[int] = orm.mapped_column(
        sa.ForeignKey("users.id"), nullable=True
    )
    store_category_id: orm.Mapped[int] = orm.mapped_column(
        sa.ForeignKey("store_categories.id")
    )

    # Columns
    store_name: orm.Mapped[str] = orm.mapped_column(
        sa.String(128),
        nullable=False,
    )
    contact_person: orm.Mapped[str] = orm.mapped_column(
        sa.String(128),
        nullable=False,
        default="",
    )
    email: orm.Mapped[str] = orm.mapped_column(
        sa.String(128),
        nullable=False,
        default="",
    )
    phone_numb: orm.Mapped[str] = orm.mapped_column(
        sa.String(128),
        nullable=False,
        default="",
    )
    country: orm.Mapped[str] = orm.mapped_column(sa.String(128), default="")
    region: orm.Mapped[str] = orm.mapped_column(sa.String(128), default="")
    city: orm.Mapped[str] = orm.mapped_column(sa.String(128), default="")
    # must check if address already exists
    address: orm.Mapped[str] = orm.mapped_column(sa.String(512), default="")
    zip: orm.Mapped[str] = orm.mapped_column(sa.String(128), default="")
    active: orm.Mapped[bool] = orm.mapped_column(sa.Boolean(), default=True)

    created_at: orm.Mapped[datetime] = orm.mapped_column(
        sa.DateTime,
        default=datetime.now,
    )

    store_category: orm.Mapped["StoreCategory"] = orm.relationship(
        back_populates="stores"
    )

    def __repr__(self):
        return f"<{self.id}: {self.store_name}>"

    @property
    def full_address(self):
        return f"{self.country}, {self.region}, {self.city}, {self.address}, {self.zip}"

    @property
    def json(self):
        return s.Store.model_validate(self).model_dump_json()

app/forms/store.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    BooleanField,
    IntegerField,
    HiddenField,
)
from wtforms.validators import DataRequired, Email


class StoreForm(FlaskForm):
    next_url = StringField("next_url")
    store_id = HiddenField("store_id", [DataRequired()])
    category_id = IntegerField("Store category", [DataRequired()])
    store_name = StringField("Name", [DataRequired()])
    contact_person = StringField("Contact person", [DataRequired()])
    email = StringField("Email", [DataRequired(), Email()])
    phone_numb = StringField("Phone number", [DataRequired()])
    country = StringField("Country")
    region = StringField("Region")
    city = StringField("City")
    address = StringField("Address", [DataRequired()])
    zip = StringField("ZIP")
    active = BooleanField("active")

    submit = SubmitField("Save")

    # def validate_address(self, field):
    #     query = (
    #         m.Store.select()
    #         .where(m.Store.address == field.data)
    #         .where(m.Store.id != int(self.store_id.data))
    #     )
    #     if db.session.scalar(query) is not None:
    #         raise ValidationError("This store address is taken.")


class NewStoreForm(FlaskForm):
    category_id = IntegerField("Store category", [DataRequired()])
    store_name = StringField("Name", [DataRequired()])
    contact_person = StringField("Contact person", [DataRequired()])
    email = StringField("Email", [DataRequired(), Email()])
    phone_numb = StringField("Phone number", [DataRequired()])
    country = StringField("Country")
    region = StringField("Region")
    city = StringField("City")
    address = StringField("Address", [DataRequired()])
    zip = StringField("ZIP")
    active = BooleanField("active")

    submit = SubmitField("Save")

    # def validate_address(self, field):
    #     query = m.Store.select().where(m.Store.address == field.data)
    #     if db.session.scalar(query) is not None:
    #         raise ValidationError("This store address is taken.")

app/views/main.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
@login_required
def index():
    return redirect(url_for("product.get_all"))


@main_blueprint.route("/no-content")
@login_required
def no_content():
    return "", 200

app/views/store.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_required, current_user
import sqlalchemy as sa
from sqlalchemy.orm import aliased
from app.controllers import create_pagination, role_required

from app import models as m, db
from app import schema as s
from app import forms as f
from app.logger import log


store_blueprint = Blueprint("store", __name__, url_prefix="/store")


@store_blueprint.route("/", methods=["GET"])
@login_required
def get_all():

    store_category = aliased(m.StoreCategory)
    q = request.args.get("q", type=str, default=None)
    query = m.Store.select().order_by(m.Store.store_name.asc())
    count_query = sa.select(sa.func.count()).select_from(m.Store)

    is_favorite = request.args.get("is_favorite", type=bool, default=False)
    if is_favorite:
        query = (
            m.Store.select()
            .join(
                m.FavoriteStoreUser,
                m.FavoriteStoreUser.store_id == m.Store.id,
            )
            .where(m.FavoriteStoreUser.user_id == current_user.id)
            .order_by(m.Store.store_name.asc())
        )
        count_query = (
            sa.select(sa.func.count())
            .join(
                m.FavoriteStoreUser,
                m.FavoriteStoreUser.store_id == m.Store.id,
            )
            .where(m.FavoriteStoreUser.user_id == current_user.id)
            .select_from(m.Store)
        )

    if q:
        query = (
            m.Store.select()
            .join(
                store_category,
                m.Store.store_category_id == store_category.id,
            )
            .where(
                m.Store.store_name.ilike(f"%{q}%")
                | m.Store.email.ilike(f"%{q}%")
                | store_category.name.ilike(f"%{q}%")
            )
            .order_by(m.Store.store_name.asc())
        )
        count_query = (
            sa.select(sa.func.count())
            .join(
                store_category,
                m.Store.store_category_id == store_category.id,
            )
            .where(
                m.Store.store_name.ilike(f"%{q}%")
                | m.Store.email.ilike(f"%{q}%")
                | store_category.name.ilike(f"%{q}%")
            )
            .select_from(m.Store)
        )

    pagination = create_pagination(total=db.session.scalar(count_query))

    stores = [
        store
        for store in db.session.execute(
            query.offset((pagination.page - 1) * pagination.per_page).limit(
                pagination.per_page
            )
        ).scalars()
    ]

    for store in stores:
        store.favorite = db.session.execute(
            sa.select(m.FavoriteStoreUser)
            .where(m.FavoriteStoreUser.user_id == current_user.id)
            .where(m.FavoriteStoreUser.store_id == store.id)
        ).scalar()
        if store.favorite:
            store.favorite = True
        else:
            store.favorite = False

    return render_template(
        "store/stores.html",
        is_favorite=is_favorite,
        stores=stores,
        page=pagination,
        search_query=q,
        current_user_id=current_user.id,
    )


@store_blueprint.route("/save/<store_id>", methods=["GET"])
@login_required
def get_edit_form(store_id: int):
    store = db.session.get(m.Store, store_id)
    if not store:
        log(log.ERROR, "Not found store by id : [%s]", store_id)
        return render_template("error_modal.html", message="Can't find store")

    store_categories = db.session.execute(m.StoreCategory.select()).scalars().all()
    form = f.StoreForm(
        store_id=store.id,
        store_name=store.store_name,
        category_id=store.store_category_id,
        contact_person=store.contact_person,
        email=store.email,
        phone_numb=store.phone_numb,
        country=store.country,
        region=store.region,
        city=store.city,
        address=store.address,
        zip=store.zip,
        active=store.active,
    )
    return render_template(
        "store/modal_edit.html", form=form, store_categories=store_categories
    )


@store_blueprint.route("/save", methods=["POST"])
@login_required
def save():
    form: f.StoreForm = f.StoreForm()
    if not form.validate_on_submit():
        log(log.ERROR, "Store save errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("store.get_all"))
    store = db.session.get(m.Store, form.store_id.data)
    if not store:
        log(
            log.ERROR,
            "Not found store by id : [%s]",
            form.store_id.data,
        )
        flash("Cannot save store data", "danger")
        return redirect(url_for("store.get_all"))

    if (
        form.category_id.data != store.store_category_id
        and db.session.get(m.StoreCategory, form.category_id.data) is None
    ):
        log(log.ERROR, "Not found store category by id: [%s]", form.category_id.data)
        flash("Cannot save store data", "danger")
        return redirect(url_for("store.get_all"))

    store.store_category_id = form.category_id.data
    store.store_name = form.store_name.data
    store.contact_person = form.contact_person.data
    store.email = form.email.data
    store.phone_numb = form.phone_numb.data
    store.country = form.country.data
    store.region = form.region.data
    store.city = form.city.data
    store.address = form.address.data
    store.zip = form.zip.data
    store.active = form.active.data
    store.save()

    if form.next_url.data:
        return redirect(form.next_url.data)
    return redirect(url_for("store.get_all"))


@store_blueprint.route("/create", methods=["GET"])
@login_required
def get_create_form():
    form: f.NewStoreForm = f.NewStoreForm()
    store_categories = db.session.execute(m.StoreCategory.select()).scalars().all()
    return render_template(
        "store/modal_add.html", form=form, store_categories=store_categories
    )


@store_blueprint.route("/create", methods=["POST"])
@login_required
def create():
    form: f.NewStoreForm = f.NewStoreForm()
    if not form.validate_on_submit():
        log(log.ERROR, "Form validation error: [%s]", form.errors)
        flash(f"Error: {form.errors}", "danger")
        return redirect(url_for("store.get_all"))
    store_category = db.session.get(m.StoreCategory, form.category_id.data)
    if not store_category:
        log(log.ERROR, "Not found store category by id: [%s]", form.category_id.data)
        flash("Cannot save store data", "danger")
        return redirect(url_for("store.get_all"))

    store = m.Store(
        store_category_id=store_category.id,
        store_name=form.store_name.data,
        contact_person=form.contact_person.data,
        email=form.email.data,
        phone_numb=form.phone_numb.data,
        country=form.country.data,
        region=form.region.data,
        city=form.city.data,
        address=form.address.data,
        zip=form.zip.data,
        active=form.active.data,
    )
    log(log.INFO, "Form submitted. Store: [%s]", store)
    flash("Store added!", "success")
    store.save()

    favorite_store: m.FavoriteStoreUser = m.FavoriteStoreUser(
        user_id=current_user.id,
        store_id=store.id,
    )
    favorite_store.save()

    return redirect(url_for("store.get_all"))


@store_blueprint.route("/delete/<int:id>", methods=["DELETE"])
@login_required
@role_required(
    [s.UserRole.ADMIN.value, s.UserRole.MANAGER.value, s.UserRole.SALES_REP.value]
)
def delete(id: int):
    """htmx"""
    store = db.session.get(m.Store, id)
    if not store:
        log(log.INFO, "There is no store with id: [%s]", id)
        return render_template(
            "toast.html", category="danger", message="Store not found"
        )

    if (
        db.session.scalars(sa.select(m.ShipRequest).where(m.ShipRequest.store_id == id))
        is not None
    ):
        log(log.INFO, "Store has ship requests. Store: [%s]", store)
        return render_template(
            "toast.html",
            category="danger",
            message="The store has ship requests dependency. Can't delete",
        )
    _ = db.session.scalars(
        sa.delete(m.FavoriteStoreUser).returning(m.FavoriteStoreUser.id)
    ).all()
    db.session.delete(store)
    db.session.commit()
    log(log.INFO, "Store deleted. Store: [%s]", s)
    return render_template("toast.html", category="success", message="Store deleted")


@store_blueprint.route("/set-favorite/<store_id>", methods=["GET"])
@login_required
def set_favorite(store_id: int):
    """htmx"""
    store = db.session.get(m.Store, store_id)
    if not store:
        log(log.INFO, "There is no store with id: [%s]", store_id)
        return render_template(
            "toast.html", category="danger", message="Error while setting favorite"
        )
    favorite_store: m.FavoriteStoreUser = db.session.scalar(
        m.FavoriteStoreUser.select().where(
            m.FavoriteStoreUser.user_id == current_user.id,
            m.FavoriteStoreUser.store_id == store_id,
        )
    )
    if favorite_store:
        db.session.delete(favorite_store)
        db.session.commit()
        return render_template("store/favorite_icon.html", store=store, favorite=False)
    favorite_store = m.FavoriteStoreUser(
        user_id=current_user.id,
        store_id=store_id,
    )
    favorite_store.save()
    return render_template("store/favorite_icon.html", store=store, favorite=True)

app/templates/store/favorite_icon.html
<div class="pl-3" hx-get="{{ url_for('store.set_favorite', store_id=store.id) }}" hx-indicator="#htmx-spinner"
    triger="click" hx-target="this" hx-swap="outerHTML">
    <label>
        <svg class="w-5 h-5 mr-2 -ml-1" fill="currentColor" viewBox="0 0 576 512" xmlns="http://www.w3.org/2000/svg">
            {% if favorite %}
            <path fill-rule="evenodd"
                d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"
                clip-rule="evenodd"></path>
            {% else %}
            <path fill-rule="evenodd"
                d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"
                clip-rule="evenodd"></path>
            {% endif %}
        </svg>
    </label>
</div>

app/templates/store/modal_add.html
<!-- Adding store modal -->
<!-- prettier-ignore-->
<div tabindex="-1" id="store-add-modal-element" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click"
  hx-swap="delete" hx-target="#store-add-modal-element"
  class="fixed bg-opacity-80 bg-gray-600 top-0 left-0 right-0 z-50 items-center justify-center w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-full max-h-full justify-end items-end flex">
  <div class="rounded-lg relative w-full max-w-2xl max-h-full bg-white" onclick="event.stopPropagation();">
    <!-- Modal content -->
    <form action="{{url_for('store.create')}}" method="post"
      class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      {{ form.hidden_tag() }}
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Add new store </h3>
        <button hx-get="{{ url_for('main.no_content') }}" hx-trigger="click" hx-swap="delete"
          hx-target="#store-add-modal-element" type="button"
          class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6 sm:col-span-3">
            <label for="store_category" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Store
              category</label>
            <select type="text" name="category_id"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Store category" required>
              {% for store_category in store_categories %}
              {% if store_category.name != "Locker" %}
              {% if loop.index == 1 %}
              <option value="{{store_category.id}}" selected>{{store_category.name}}</option>
              {% else %}
              <option value="{{store_category.id}}">{{store_category.name}}</option>
              {% endif %}
              {% endif %}
              {% endfor %}
            </select>
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="store_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" name="store_name"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Name" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="contact_person" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contact
              person</label>
            <input type="text" name="contact_person"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Contact person" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
            <input type="email" name="email"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="example@company.com" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="phone_numb" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Phone
              number</label>
            <input type="text" name="phone_numb"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="contact_number" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="country" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Country</label>
            <input type="text" name="country"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="country" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="region" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Region</label>
            <input type="text" name="region"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="region" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="city" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">City</label>
            <input type="text" name="city"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="city" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="address" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Address</label>
            <input type="text" name="address"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="address" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="zip" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Postal Code</label>
            <input type="text" name="zip"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="zip" required />
          </div>
          <div class="col-span-6 sm:col-span-3">
            <label for="active" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Active</label>
            <input type="checkbox" name="active"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block  p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button name="submit" type="submit"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Save all </button>
      </div>
    </form>
  </div>
</div>