app/models/assign.py
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import orm

from app.database import db
from .utils import ModelMixin, generate_uuid
from app import schema as s
from .product import Product
from .group import Group
from .user import User


class Assign(db.Model, ModelMixin):
    __tablename__ = "assigns"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    # Foreign keys
    product_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("products.id"))
    from_group_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("groups.id"))
    group_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("groups.id"))
    user_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("users.id"))
    bulk_assign_id: orm.Mapped[int | None] = orm.mapped_column(
        sa.ForeignKey("bulk_assigns.id")
    )
    # Columns
    quantity: orm.Mapped[int] = orm.mapped_column(sa.Integer)
    type: orm.Mapped[str] = orm.mapped_column(sa.String(64))
    created_at: orm.Mapped[datetime] = orm.mapped_column(
        sa.DateTime,
        default=datetime.now,
    )
    uuid: orm.Mapped[str] = orm.mapped_column(sa.String(64), default=generate_uuid)
    # Relationships
    product: orm.Mapped[Product] = orm.relationship()
    from_group: orm.Mapped[Group] = orm.relationship(
        "Group", foreign_keys=[from_group_id]
    )
    group: orm.Mapped[Group] = orm.relationship("Group", foreign_keys=[group_id])
    user: orm.Mapped[User] = orm.relationship("User")

    @property
    def json(self):
        return s.Assign.model_validate(self).model_dump_json(by_alias=True)

app/models/image.py
import base64
from io import BytesIO
from pathlib import Path
from PIL import Image as PilImage
import sqlalchemy as sa
from sqlalchemy import orm

from app.database import db
from .utils import ModelMixin


class Image(db.Model, ModelMixin):
    __tablename__ = "images"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)

    name: orm.Mapped[str] = orm.mapped_column(
        sa.String(256),
        unique=True,
        nullable=False,
    )
    path: orm.Mapped[str] = orm.mapped_column(
        sa.String(256),
        nullable=False,
    )
    extension: orm.Mapped[str] = orm.mapped_column(
        sa.String(32),
        nullable=False,
    )

    def get_base64(self):
        image_path = Path("app") / "static" / "img" / "product" / self.name
        if Path(self.path).is_file():
            image_path = Path(self.path)
        elif not image_path.is_file():
            image_path = Path("app") / "static" / "img" / "no_picture_default.png"

        with PilImage.open(
            image_path,
        ).resize((200, 200)) as original_image:
            filename = self.name + "." + self.extension
            with BytesIO() as buffered:
                buffered.name = filename
                original_image.save(buffered)
                return base64.b64encode(buffered.getvalue())

    def __repr__(self):
        return f"<{self.id}: {self.name}>"

app/forms/request_share.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class RequestShareForm(FlaskForm):
    next_url = StringField("next_url")
    request_share_id = StringField("request_share_id", [DataRequired()])
    product_id = StringField("Product")
    group_id = IntegerField("Group")
    desire_quantity = IntegerField("Desire Quantity", [DataRequired()])
    status = StringField("Status")

    submit = SubmitField("Save")

app/controllers/image.py
import base64
from io import BytesIO
from pathlib import Path
import os
from PIL import Image

from app.logger import log


BASE_IMAGE_PATH = Path("app/static/img/")


def save_image(image: BytesIO, path: str) -> tuple[str, str]:
    """Save image to disk and return the path and extension."""
    log(log.INFO, "Saving image.")

    image_path = BASE_IMAGE_PATH / path

    with open(image_path, "wb") as f:
        read = image.read()
        f.write(read)
        image_string = base64.b64encode(read).decode()
    return str(image_path), image_string


def find_image(directory, image_name):
    """
    Search for an image by name within a specified directory.

    Parameters:
    directory (str): The directory to search within.
    image_name (str): The name of the image file to search for (e.g., 'example.jpg').

    Returns:
    str: The path of the found image file, or None if not found.
    """
    path = BASE_IMAGE_PATH / directory
    log(log.INFO, f"Searching for image {image_name} in directory {path}.")

    for root, _, files in os.walk(path):
        for file in files:
            if image_name in file:
                try:
                    # Try to open the file with PIL to ensure it's an image
                    with Image.open(os.path.join(root, file)):
                        return str(os.path.join(root, file))
                except IOError:
                    # If the file is not an image, continue searching
                    continue
    return None

app/views/assign.py
from flask import (
    Blueprint,
    render_template,
    request,
)
from flask_login import login_required, current_user
import sqlalchemy as sa
from sqlalchemy.orm import aliased
from app.controllers import create_pagination, role_required

from app import models as m, db
from app import schema as s


assign_blueprint = Blueprint("assign", __name__, url_prefix="/assign")


@assign_blueprint.route("/", methods=["GET"])
@login_required
@role_required(
    [
        s.UserRole.ADMIN.value,
        s.UserRole.MANAGER.value,
        s.UserRole.SALES_REP.value,
    ]
)
def get_all():
    product = aliased(m.Product)
    group = aliased(m.Group)
    q = request.args.get("q", type=str, default=None)
    stm_where = sa.or_(
        m.Assign.user_id == current_user.id,
    )
    if current_user.role_obj.role_name == s.UserRole.ADMIN.value:
        stm_where = sa.true()

    query = m.Assign.select().where(stm_where).order_by(m.Assign.id.desc())
    count_query = sa.select(sa.func.count()).where(stm_where).select_from(m.Assign)
    if q:
        query = (
            m.Assign.select()
            .join(
                product,
                m.Assign.product_id == product.id,
            )
            .join(group, m.Assign.group_id == group.id)
            .where(
                product.name.ilike(f"%{q}%")
                | group.name.ilike(f"%{q}%")
                | m.Assign.uuid.ilike(f"%{q}%")
            )
            .order_by(m.Assign.id)
        )
        count_query = (
            sa.select(sa.func.count())
            .join(
                product,
                m.Assign.product_id == product.id,
            )
            .join(group, m.Assign.group_id == group.id)
            .where(
                product.name.ilike(f"%{q}%")
                | group.name.ilike(f"%{q}%")
                | m.Assign.uuid.ilike(f"%{q}%")
            )
            .select_from(m.Assign)
        )

    pagination = create_pagination(total=db.session.scalar(count_query))

    return render_template(
        "assign/assigns.html",
        assigns=db.session.execute(
            query.offset((pagination.page - 1) * pagination.per_page).limit(
                pagination.per_page
            )
        ).scalars(),
        page=pagination,
        search_query=q,
    )

app/views/cart.py
import json
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
)
from flask_login import login_required, current_user
import sqlalchemy as sa
from app.controllers import (
    create_pagination,
    role_required,
    get_query_params_from_headers,
)

from app import models as m, db

from app import schema as s
from app import forms as f
from app.logger import log
from config import SALES_REP_LOCKER_NAME


cart_blueprint = Blueprint("cart", __name__, url_prefix="/cart")


@cart_blueprint.route("/", methods=["GET"])
@login_required
@role_required(
    [
        s.UserRole.ADMIN.value,
        s.UserRole.SALES_REP.value,
        s.UserRole.WAREHOUSE_MANAGER.value,
        s.UserRole.MANAGER.value,
    ]
)
def get_all():
    form = f.CartForm()

    q = request.args.get("q", type=str, default=None)
    query = (
        sa.select(m.Cart)
        .where(
            m.Cart.status == s.CartStatus.PENDING.value,
            m.Cart.user_id == current_user.id,
        )
        .order_by(m.Cart.id)
    )
    count_query = sa.select(sa.func.count()).select_from(m.Cart)
    if q:
        query = (
            m.Cart.select().where(m.Cart.order_numb.ilike(f"%{q}%")).order_by(m.Cart.id)
        )
        count_query = (
            sa.select(sa.func.count())
            .where(m.Cart.order_numb.ilike(f"%{q}%"))
            .select_from(m.Cart)
        )

    locker_id = db.session.execute(
        m.StoreCategory.select()
        .where(m.StoreCategory.name == SALES_REP_LOCKER_NAME)
        .with_only_columns(m.StoreCategory.id)
    ).scalar()

    pagination = create_pagination(total=db.session.scalar(count_query))

    stores = db.session.scalars(
        m.Store.select().where(m.Store.store_category_id != locker_id)
    ).all()

    for store in stores:
        store.favorite = db.session.execute(
            sa.select(m.FavoriteStoreUser)
            .where(m.FavoriteStoreUser.user_id == current_user.id)
            .where(m.FavoriteStoreUser.store_id == store.id)
        ).scalar()
        if store.favorite:
            store.favorite = True
        else:
            store.favorite = False

    store_categories = db.session.scalars(
        sa.select(m.StoreCategory).where(m.StoreCategory.id != locker_id)
    ).all()

    is_locker_store_category = False

    if (
        current_user.role_obj.role_name == s.UserRole.SALES_REP.value
        and db.session.execute(
            m.Store.select().where(m.Store.user_id == current_user.id)
        )
        is not None
    ):
        is_locker_store_category = True

    cart_items = db.session.scalars(
        query.offset((pagination.page - 1) * pagination.per_page).limit(
            pagination.per_page
        )
    ).all()
    event_carts = [
        {
            "group": cart.group.name,
            "id": cart.id,
            "quantity": cart.quantity,
            "product_id": cart.product_id,
        }
        for cart in cart_items
        if cart.group.master_group.name == s.Events.name.value
    ]

    return render_template(
        "cart.html",
        cart_items=cart_items,
        page=pagination,
        form=form,
        stores=stores,
        store_categories=store_categories,
        carts=json.dumps(event_carts),
        is_locker_store_category=is_locker_store_category,
    )


@cart_blueprint.route("/get-base-select", methods=["GET"])
@login_required
@role_required(
    [
        s.UserRole.SALES_REP.value,
    ]
)
def get_base_select():
    """htmx"""
    locker_id = db.session.execute(
        m.StoreCategory.select()
        .where(m.StoreCategory.name == SALES_REP_LOCKER_NAME)
        .with_only_columns(m.StoreCategory.id)
    ).scalar()

    stores = db.session.scalars(
        m.Store.select().where(m.Store.store_category_id != locker_id)
    ).all()

    store_categories = db.session.scalars(
        sa.select(m.StoreCategory).where(m.StoreCategory.id != locker_id)
    ).all()

    return render_template(
        "cart/base_select.html",
        store_categories=store_categories,
        stores=stores,
        is_locker_store_category=True,
    )


@cart_blueprint.route("/ship-to-locker", methods=["GET"])
@login_required
@role_required(
    [
        s.UserRole.SALES_REP.value,
    ]
)
def get_ship_to_locker():
    """htmx"""
    stores = db.session.scalars(
        sa.select(m.Store).where(m.Store.user_id == current_user.id)
    ).all()

    store_categories = db.session.scalars(
        sa.select(m.StoreCategory)
        .join(m.Store)
        .where(m.Store.user_id == current_user.id)
    ).all()

    return render_template(
        "cart/locker_select.html",
        is_locker_store_category=True,
        store_categories=store_categories,
        stores=stores,
    )


@cart_blueprint.route("/get-stores", methods=["GET"])
@login_required
@role_required(
    [
        s.UserRole.ADMIN.value,
        s.UserRole.SALES_REP.value,
        s.UserRole.WAREHOUSE_MANAGER.value,
        s.UserRole.MANAGER.value,
    ]
)
def get_stores_options():
    """htmx"""

    category_id = request.args.get("store_category", type=str, default=None)
    is_favorites = request.args.get("is_favorites", type=bool, default=False)
    query = (
        sa.select(m.Store)
        .join(m.StoreCategory)
        .where(m.StoreCategory.name != SALES_REP_LOCKER_NAME)
    )
    if category_id:
        query = query.where(m.Store.store_category_id == category_id)

    if is_favorites:
        query = query.where(
            m.Store.id.in_(
                db.session.execute(
                    sa.select(m.FavoriteStoreUser.store_id).where(
                        m.FavoriteStoreUser.user_id == current_user.id
                    )
                ).scalars()
            )
        )

    stores = db.session.scalars(query.order_by(m.Store.store_name)).all()

    return render_template("cart/store_options.html", stores=stores)


@cart_blueprint.route("/create", methods=["POST"])
@login_required
@role_required(
    [
        s.UserRole.ADMIN.value,
        s.UserRole.MANAGER.value,
        s.UserRole.SALES_REP.value,
    ]
)
def create():
    form: f.NewCartForm = f.NewCartForm()
    query_params = get_query_params_from_headers()

    if not form.validate_on_submit():
        log(log.ERROR, "Item creation errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("product.get_all", **query_params))

    warehouse_product = db.session.get(
        m.WarehouseProduct, form.warehouse_product_id.data
    )

    if not warehouse_product:
        log(log.ERROR, "Not found warehouse products")
        return render_template(
            "error_modal.html", message="Can't find product warehouse"
        )

    is_event = False
    if warehouse_product.group.master_group.name == s.Events.name.value:
        is_event = True

    available_quantity = warehouse_product.available_quantity

    if form.quantity.data > available_quantity:
        flash("Not enough products in stock", "danger")
        return redirect(url_for("product.get_all"))

    cart_product_amount = (
        db.session.execute(
            sa.select(sa.func.sum(m.Cart.quantity)).where(
                m.Cart.user_id == current_user.id,
                m.Cart.product_id == warehouse_product.product_id,
                m.Cart.group_id == warehouse_product.group_id,
                m.Cart.status == s.CartStatus.PENDING.value,
            )
        ).scalar()
        or 0
    )
    new_quantity = int(form.quantity.data)

    if (cart_product_amount + new_quantity) > available_quantity:
        log(log.ERROR, "The cart is full,not enough products in stock")
        flash("The cart is full, not enough products in stock", "danger")
        return redirect(url_for("product.get_all"))

    item = m.Cart(
        product_id=warehouse_product.product_id,
        group_id=warehouse_product.group_id,
        quantity=new_quantity,
        user_id=current_user.id,
    )
    log(log.INFO, "Form submitted. Cart: [%s]", item)
    item.save()
    flash("Item added!", "success")
    if is_event:
        return redirect(url_for("product.get_all", is_event="true", **query_params))
    return redirect(url_for("product.get_all", **query_params))


@cart_blueprint.route("/edit", methods=["POST"])
@login_required
@role_required(
    [
        s.UserRole.ADMIN.value,
        s.UserRole.MANAGER.value,
        s.UserRole.SALES_REP.value,
    ]
)
def save():
    form: f.CartForm = f.CartForm()
    if not form.validate_on_submit():
        log(log.ERROR, "Cart item save errors: [%s]", form.errors)
        flash(f"{form.errors}", "danger")
        return redirect(url_for("cart.get_all"))

    cart = db.session.scalar(
        sa.select(m.Cart).where(m.Cart.id == int(form.cart_id.data))
    )

    if not cart:
        log(log.ERROR, "Not found cart item by id : [%s]", form.cart_id.data)
        flash("Cannot save item data", "danger")
        return redirect(url_for("cart.get_all"))

    available_quantity = cart.available_quantity

    if not available_quantity:
        log(log.ERROR, "Not enough products in stock")
        flash("Cannot save item data", "danger")
        return redirect(url_for("cart.get_all"))

    cart_product_amount = (
        db.session.execute(
            sa.select(sa.func.sum(m.Cart.quantity)).where(
                m.Cart.id != cart.id,
                m.Cart.user_id == current_user.id,
                m.Cart.product_id == cart.product_id,
                m.Cart.group_id == cart.group_id,
                m.Cart.status == s.CartStatus.PENDING.value,
            )
        ).scalar()
        or 0
    )
    if (
        form.quantity.data > available_quantity
    ) or cart_product_amount + form.quantity.data > available_quantity:
        log(log.ERROR, "The cart is full, not enough products in stock")
        flash("The cart is full, not enough products in stock", "danger")
        return redirect(url_for("cart.get_all"))

app/views/main.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
@login_required
def index():
    return redirect(url_for("product.get_all"))


@main_blueprint.route("/no-content")
@login_required
def no_content():
    return "", 200

app/templates/product/assing_sub_groups.html
{% if sub_groups | length > 0 %}
<div class="col-span-6 sm:col-span-2" id="sub-group-element">
  <label for="sub_group" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sub Group</label>
  <input type="text" list="assign-sub-group-list-data" autocomplete="off" name="sub_group" placeholder="Select group"
    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
  <datalist id="assign-sub-group-list-data">
    <option value="" selected disabled>Sub Group</option>
    {% for group in sub_groups %}
    <option value="{{ group.name }}">
      {% endfor %}
  </datalist>
</div>
{% else %}
<div class="col-span-6 sm:col-span-2" id="sub-group-element"></div>
{% endif %}

app/templates/product/modal_event.html
<!-- event product modal -->
<!-- prettier-ignore-->
<!-- Modal content -->
<!-- TODO change action for event form -->
<div tabindex="-1" id="product-event-modal-element" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click"
  hx-swap="delete" hx-target="#product-event-modal-element"
  class="fixed bg-opacity-80 bg-gray-600 top-0 left-0 right-0 z-50 items-center justify-center w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-full max-h-full justify-end items-end flex">
  <div class="rounded-lg relative w-full max-w-2xl max-h-full bg-white" onclick="event.stopPropagation();">
    <form action="{{ url_for('cart.create')}}" method="post"
      class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      {{ form.hidden_tag() }}
      {{ form.warehouse_product_id }}
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white"> Booking product </h3>
        <button type="button" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click" hx-swap="delete"
          hx-target="#product-event-modal-element"
          class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <div class="grid grid-cols-6 gap-6">
          <div data-target-product-id="{{ warehouse_product.product.id }}"
            class="product-full-image-anchor product-full-image-anchor col-span-6 sm:col-span-2 sm:row-span-2 max-height-image-container">
            {% if warehouse_product.product.image and warehouse_product.product.image | length > 100 %}
            <img src="data:image/png;base64, {{ warehouse_product.product.image }}"
              class="w-full h-full object-cover" />
            {% else %}
            <img
              src="https://raw.githubusercontent.com/Simple2B/BeamSuntory/develop/app/static/img/no_picture_default.png"
              class="w-full h-full object-cover" />
            {% endif %}
          </div>
          <div class="col-span-6 sm:col-span-4 ">
            <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Product Name</label>
            <div
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              {{ warehouse_product.product.name }}</div>
          </div>
          <div class="col-span-6 sm:col-span-4">
            <label for="SKU" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">SKU</label>
            <div
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
              {{ warehouse_product.product.SKU }}</div>
          </div>
          <div class="sm:col-start-2 sm:col-end-6 col-span-6">
            <input id="datepicker-event" data-product-id="{{ warehouse_product.product.id }}"
              data-group-name="{{ warehouse_product.group.name }}" class="datepicker invisible" required readonly />
          </div>
          <div class="col-span-6 sm:col-span-6">
            <label for="height" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Desired
              Quantity</label>
            <input type="number" name="quantity"
              class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Desired quantity" min="0" max="{{ warehouse_product.product_quantity }}" required />
          </div>
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex items-center p-6 space-x-2 border-t border-gray-200 rounded-b dark:border-gray-600">
        <button type="submit" id="product-event-submit-btn"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          Add to card </button>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/@easepick/datetime@1.2.1/dist/index.umd.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@easepick/core@1.2.1/dist/index.umd.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@easepick/base-plugin@1.2.1/dist/index.umd.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@easepick/lock-plugin@1.2.1/dist/index.umd.min.js"></script>

      <script src="{{ url_for('static', filename='js/product_event.js') }}" type="text/javascript" defer></script>
    </form>
  </div>
</div>

app/templates/product/product_master_group.html
<div class="group-item p-6 space-y-6 border-t">
    <div class="grid grid-cols-12 gap-5">
        <div class="col-span-6 sm:col-span-4">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Master
                Group</label>
            <select type="text" name="master_group_id" hx-get="{{ url_for('product.htmx.get_product_group') }}"
                hx-trigger="change" hx-spinner="#htmx-spinner" hx-swap="outerHTML"
                hx-target="next .product-group-edit-item" hx-indicator="#htmx-spinner"
                class=" shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Master
        Group" required>
                {% for master_group in master_product_groups %}
                <option value="{{ master_group.id }}">{{ master_group.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-span-6 sm:col-span-4 product-group-edit-item">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Group</label>
            <select type="text" name="add_group"
                class="product_group_id shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Group" required>
                {% for sub_group in sub_groups %}
                <option value="{{ sub_group.id }}">{{ sub_group.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-span-6 sm:col-span-4">
            <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Action</label>
            <button type="button" hx-get="{{ url_for('main.no_content') }}" hx-trigger="click" hx-swap="delete"
                hx-target="closest .group-item" hx-indicator="#htmx-spinner"
                class=" inline-flex items-center px-3 py-2 mr-3 text-sm font-medium text-center text-white rounded-lg bg-red-600 hover:bg-red-800 focus:ring-4 focus:ring-red-300 dark:focus:ring-red-900">
                <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z">
                    </path>
                </svg>
            </button>
            <button type="button" hx-get="{{ url_for('product.htmx.get_product_master_groups') }}" hx-trigger="click"
                hx-swap="beforeend" hx-target="#product-group-edit-container" hx-indicator="#htmx-spinner"
                class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-red-300">
                <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M64 80c-8.8 0-16 7.2-16 16V416c0 8.8 7.2 16 16 16H384c8.8 0 16-7.2 16-16V96c0-8.8-7.2-16-16-16H64zM0 96C0 60.7 28.7 32 64 32H384c35.3 0 64 28.7 64 64V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96zM200 344V280H136c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V168c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H248v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z">
                    </path>
                </svg>
            </button>
        </div>
    </div>
</div>